services:
  angular-material-extensions:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "4200:4200"
      - "49153:49153"
    tty: true
